/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/Models/Building3Night.glb')
  const standardMaterial = new MeshStandardMaterial({ metalness: 1.0, roughness: 0.2, color: '#131313' })
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Office_Building_2_1.geometry}
          material={standardMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Office_Building_2_2.geometry}
          material={materials.M_Black_Frames}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Office_Building_2_3.geometry}
          material={materials.M_Windows_Night}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/Models/Building3Night.glb')