/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/Models/Building1.glb')
  
  // 모든 메쉬에 적용할 공통 material 생성
  const standardMaterial = new MeshStandardMaterial({ 
    metalness: 1.0, 
    roughness: 0.2, 
    color: '#020f10' 
  })

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_001_1.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_001_2.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_002_1.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_002_2.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_003_1.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_003_2.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_004_1.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_004_2.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_005_1.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_005_2.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_006_1.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_006_2.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_007_1.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_007_2.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_008_1.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_008_2.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_009_1.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_009_2.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_010_1.geometry}
        material={standardMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Residential_Buildings_010_2.geometry}
        material={standardMaterial}
      />
    </group>
  )
}

useGLTF.preload('/assets/Models/Building1.glb')