/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshStandardMaterial } from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets/Models/Building2.glb')
  
  // 모든 메쉬에 적용할 공통 material 생성
  const standardMaterial = new MeshStandardMaterial({ metalness: 1.0, roughness: 0.2, color: '#020f10' })

  return (
    <group {...props} dispose={null}>
      <group position={[-6.2, 3.5, 11.59]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056.geometry}
          material={standardMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube056_1.geometry}
          material={standardMaterial}
        />
      </group>
      <group position={[-6.2, 14.3, 11.59]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059.geometry}
          material={standardMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_1.geometry}
          material={standardMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_2.geometry}
          material={standardMaterial}
        />
      </group>
      <group position={[-6.2, 10.7, 11.59]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059.geometry}
          material={standardMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_1.geometry}
          material={standardMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_2.geometry}
          material={standardMaterial}
        />
      </group>
      <group position={[-6.2, 7.1, 11.59]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059.geometry}
          material={standardMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_1.geometry}
          material={standardMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube059_2.geometry}
          material={standardMaterial}
        />
      </group>
      <group position={[-6.2, 17.9, 11.59]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060.geometry}
          material={standardMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_1.geometry}
          material={standardMaterial}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube060_2.geometry}
          material={standardMaterial}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/Models/Building2.glb')