/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Model = forwardRef(function Model(props, ref) {
  const { nodes, materials } = useGLTF('/assets/Models/Utopia.glb')
  return (
      <group ref={ref} {...props}>  
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.기둥.geometry}
        material={materials['Material.008']}
        position={[0, 1.817, 0]}
        rotation={[0, -0.314, 0]}
        scale={[1.29, 1.152, 1.29]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.바닥.geometry}
        material={materials.뚜껑창문}
        position={[0, 0.061, 0]}
        rotation={[0, -0.314, 0]}
        scale={[7.365, 0.127, 7.365]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.뚜껑.geometry}
        material={materials.안장}
        position={[0.008, 5.037, 0.009]}
        scale={[9.929, 0.074, 9.929]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.밑바닥.geometry}
        material={materials.뚜껑옆}
        position={[0, -0.111, 0]}
        rotation={[-Math.PI, 0.314, -Math.PI]}
        scale={[9.093, 0.103, 9.093]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials.기둥}
        position={[-2.701, 2.557, 7.942]}
        rotation={[0, 1.541, 0]}
        scale={[0.132, 2.592, 0.132]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder032.geometry}
        material={materials['Material.006']}
        position={[0, 4.752, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-6.717, -0.209, -6.717]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder033.geometry}
        material={materials.레이스}
        position={[0.001, 2.963, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1.583, -0.049, -1.583]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials['Branch 기둥']}
        position={[0.912, 1.599, 1.185]}
        rotation={[0, -0.889, 0]}
        scale={[-0.063, -0.044, -0.063]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.뚜껑뿔.geometry}
        material={materials.레이스}
        position={[-10.5, 6.065, 3.438]}
        scale={0.189}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder030.geometry}
        material={materials['Material.007']}
        position={[0.001, 4.429, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-6.486, -0.201, -6.486]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder034.geometry}
        material={materials.뚜껑창문}
        position={[0.001, 5.379, 0]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-6.486, -0.201, -6.486]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.울타리}
        position={[-8.046, 0.433, 2.537]}
        rotation={[Math.PI / 2, 0, 1.272]}
        scale={[2.783, 2.783, 0.355]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials['Material.009']}
        position={[-0.003, 0.905, -0.003]}
        rotation={[0, 0.625, 0]}
        scale={[1.867, 0.64, 1.867]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCircle016.geometry}
        material={materials.Brass}
        position={[-0.459, 0.057, 4.778]}
        rotation={[0, -0.314, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCircle015.geometry}
        material={materials.Brass}
        position={[-0.505, 0.056, 4.777]}
        rotation={[0, -0.314, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCircle007.geometry}
        material={materials.Brass}
        position={[-0.459, 0.057, 4.778]}
        rotation={[0, -0.314, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCircle006.geometry}
        material={materials.Brass}
        position={[-0.505, 0.056, 4.777]}
        rotation={[0, -0.314, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BezierCircle003.geometry}
        material={materials.Brass}
        position={[-0.39, -0.588, 2.937]}
        rotation={[0, -0.314, 0]}
      />
      <group position={[16, 17.306, 20.841]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retopo_Horse001.geometry}
          material={materials.horse}
          position={[-14.127, -16.201, -14.984]}
          rotation={[-Math.PI, 1.264, -Math.PI]}
          scale={1.361}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retopo_Horse002.geometry}
          material={materials.horse}
          position={[-21.335, -16.201, -17.239]}
          rotation={[0, 0.614, 0]}
          scale={1.361}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retopo_Horse003.geometry}
          material={materials.horse}
          position={[-9.771, -16.201, -20.733]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={1.361}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retopo_Horse004.geometry}
          material={materials.horse}
          position={[-21.047, -16.201, -24.624]}
          rotation={[0, -0.666, 0]}
          scale={1.361}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Retopo_Horse005.geometry}
          material={materials.horse}
          position={[-13.994, -16.201, -26.858]}
          rotation={[Math.PI, -1.248, Math.PI]}
          scale={1.361}
        />
      </group>
      <group position={[14.532, -1.273, -27.254]}>
        <mesh
          name="horse_statue_01"
          castShadow
          receiveShadow
          geometry={nodes.horse_statue_01.geometry}
          material={materials.horse_statue_01}
          morphTargetDictionary={nodes.horse_statue_01.morphTargetDictionary}
          morphTargetInfluences={nodes.horse_statue_01.morphTargetInfluences}
          position={[-10.903, 1.24, 29.734]}
          rotation={[0, 0.86, 0]}
          scale={15.032}
        />
        <mesh
          name="horse_statue_01001"
          castShadow
          receiveShadow
          geometry={nodes.horse_statue_01001.geometry}
          material={materials.horse_statue_01}
          morphTargetDictionary={nodes.horse_statue_01001.morphTargetDictionary}
          morphTargetInfluences={nodes.horse_statue_01001.morphTargetInfluences}
          position={[-15.967, 1.24, 31.437]}
          rotation={[0, -0.266, 0]}
          scale={15.032}
        />
        <mesh
          name="horse_statue_01002"
          castShadow
          receiveShadow
          geometry={nodes.horse_statue_01002.geometry}
          material={materials.horse_statue_01}
          morphTargetDictionary={nodes.horse_statue_01002.morphTargetDictionary}
          morphTargetInfluences={nodes.horse_statue_01002.morphTargetInfluences}
          position={[-19.173, 1.24, 27.058]}
          rotation={[0, -1.463, 0]}
          scale={15.032}
        />
        <mesh
          name="horse_statue_01003"
          castShadow
          receiveShadow
          geometry={nodes.horse_statue_01003.geometry}
          material={materials.horse_statue_01}
          morphTargetDictionary={nodes.horse_statue_01003.morphTargetDictionary}
          morphTargetInfluences={nodes.horse_statue_01003.morphTargetInfluences}
          position={[-15.923, 1.24, 22.99]}
          rotation={[Math.PI, -0.407, Math.PI]}
          scale={15.032}
        />
        <mesh
          name="horse_statue_01004"
          castShadow
          receiveShadow
          geometry={nodes.horse_statue_01004.geometry}
          material={materials.horse_statue_01}
          morphTargetDictionary={nodes.horse_statue_01004.morphTargetDictionary}
          morphTargetInfluences={nodes.horse_statue_01004.morphTargetInfluences}
          position={[-10.837, 1.24, 24.626]}
          rotation={[-Math.PI, 0.887, -Math.PI]}
          scale={15.032}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder045.geometry}
        material={nodes.Cylinder045.material}
        position={[-2.805, 0.097, -8.489]}
        scale={[0.094, 0.129, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder046.geometry}
        material={nodes.Cylinder046.material}
        position={[2.749, 0.097, -8.562]}
        scale={[0.094, 0.129, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder047.geometry}
        material={nodes.Cylinder047.material}
        position={[7.269, 0.08, -5.303]}
        scale={[0.094, 0.129, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder048.geometry}
        material={nodes.Cylinder048.material}
        position={[8.98, 0.097, -0.016]}
        scale={[0.094, 0.129, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder049.geometry}
        material={nodes.Cylinder049.material}
        position={[7.274, 0.097, 5.273]}
        scale={[0.094, 0.129, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder050.geometry}
        material={nodes.Cylinder050.material}
        position={[2.785, 0.097, 8.493]}
        scale={[0.094, 0.129, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder051.geometry}
        material={nodes.Cylinder051.material}
        position={[-2.771, 0.097, 8.515]}
        scale={[0.094, 0.129, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder052.geometry}
        material={nodes.Cylinder052.material}
        position={[-7.284, 0.049, 5.278]}
        scale={[0.094, 0.129, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder053.geometry}
        material={nodes.Cylinder053.material}
        position={[-8.954, 0.073, 0.001]}
        scale={[0.094, 0.129, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder054.geometry}
        material={nodes.Cylinder054.material}
        position={[-7.239, 0.097, -5.252]}
        scale={[0.094, 0.129, 0.094]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder061.geometry}
        material={materials['GOLD meterial']}
        position={[-10.829, 7.164, 0.012]}
        rotation={[-2.972, 0.43, 2.804]}
        scale={[-0.013, -0.009, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.뚜껑옆}
        position={[10.774, 5.655, 0.019]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials.mirror}
        position={[10.895, 5.655, 0.019]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials.뚜껑옆}
        position={[8.743, 5.655, -6.327]}
        rotation={[Math.PI, -0.633, 0]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials.mirror}
        position={[8.864, 5.655, -6.327]}
        rotation={[Math.PI, -0.633, 0]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[10.774, 5.655, 0.019]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[10.895, 5.655, 0.019]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[8.743, 5.655, -6.327]}
        rotation={[Math.PI, -0.633, 0]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[8.864, 5.655, -6.327]}
        rotation={[Math.PI, -0.633, 0]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials.mirror}
        position={[3.508, 5.655, -10.33]}
        rotation={[Math.PI, -1.26, 0]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[-3.137, 5.655, -10.309]}
        rotation={[0, -1.249, -Math.PI]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={materials.뚜껑옆}
        position={[-8.759, 5.655, -6.383]}
        rotation={[0, -0.634, -Math.PI]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[-8.638, 5.655, -6.383]}
        rotation={[0, -0.634, -Math.PI]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        material={materials.뚜껑옆}
        position={[-10.865, 5.655, -0.018]}
        rotation={[0, -0.001, -Math.PI]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        position={[-10.744, 5.655, -0.018]}
        rotation={[0, -0.001, -Math.PI]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[-8.759, 5.655, -6.383]}
        rotation={[0, -0.634, -Math.PI]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        position={[-8.638, 5.655, -6.383]}
        rotation={[0, -0.634, -Math.PI]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        position={[-10.865, 5.655, -0.018]}
        rotation={[0, -0.001, -Math.PI]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        material={nodes.Cube024.material}
        position={[-10.744, 5.655, -0.018]}
        rotation={[0, -0.001, -Math.PI]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube025.geometry}
        material={nodes.Cube025.material}
        position={[-8.72, 5.655, 6.338]}
        rotation={[0, 0.626, -Math.PI]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={nodes.Cube026.material}
        position={[-3.286, 5.655, 10.3]}
        rotation={[0, 1.259, -Math.PI]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={materials.뚜껑옆}
        position={[-8.841, 5.655, 6.338]}
        rotation={[0, 0.626, -Math.PI]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={materials.뚜껑옆}
        position={[-3.407, 5.655, 10.3]}
        rotation={[0, 1.259, -Math.PI]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={materials.mirror}
        position={[-3.346, 5.692, -10.403]}
        rotation={[-Math.PI, 1.259, 0]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        material={materials.mirror}
        position={[-8.771, 5.648, -6.429]}
        rotation={[-Math.PI, 0.633, 0]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        material={materials.mirror}
        position={[-10.924, 5.655, 0.07]}
        rotation={[-Math.PI, 0.009, 0]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        material={materials.mirror}
        position={[-8.863, 5.559, 6.391]}
        rotation={[Math.PI, -0.618, 0]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        material={materials.mirror}
        position={[-3.363, 5.704, 10.357]}
        rotation={[0, 1.255, -Math.PI]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        material={materials.뚜껑옆}
        position={[3.391, 5.679, 10.274]}
        rotation={[-Math.PI, 1.261, 0]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        material={materials.mirror}
        position={[3.436, 5.728, 10.331]}
        rotation={[-Math.PI, 1.265, 0]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        material={nodes.Cube037.material}
        position={[8.762, 5.659, 6.34]}
        rotation={[-Math.PI, 0.624, 0]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        material={materials.mirror}
        position={[8.806, 5.708, 6.396]}
        rotation={[-Math.PI, 0.628, 0]}
        scale={[-0.043, -0.969, -2.831]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials['GOLD meterial']}
        position={[-8.808, 7.164, -6.352]}
        rotation={[-2.839, 1.03, 2.613]}
        scale={[-0.013, -0.009, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={materials['GOLD meterial']}
        position={[-3.28, 7.164, -10.353]}
        rotation={[-0.957, 1.382, 0.682]}
        scale={[-0.013, -0.009, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={materials['GOLD meterial']}
        position={[3.389, 7.164, -10.369]}
        rotation={[-0.227, 0.821, -0.099]}
        scale={[-0.013, -0.009, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={materials['GOLD meterial']}
        position={[8.786, 7.164, -6.36]}
        rotation={[-0.157, 0.189, -0.237]}
        scale={[-0.013, -0.009, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={materials['GOLD meterial']}
        position={[10.848, 7.164, 0.014]}
        rotation={[-0.169, -0.425, -0.337]}
        scale={[-0.013, -0.009, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={materials['GOLD meterial']}
        position={[8.809, 7.164, 6.357]}
        rotation={[-0.287, -0.997, -0.51]}
        scale={[-0.013, -0.009, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={materials['GOLD meterial']}
        position={[3.42, 7.164, 10.311]}
        rotation={[-2.223, -1.376, -2.499]}
        scale={[-0.013, -0.009, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={materials['GOLD meterial']}
        position={[-3.396, 7.164, 10.311]}
        rotation={[-2.915, -0.82, 3.042]}
        scale={[-0.013, -0.009, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={materials['GOLD meterial']}
        position={[-8.87, 7.164, 6.364]}
        rotation={[-2.984, -0.203, 2.907]}
        scale={[-0.013, -0.009, -0.013]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube039.geometry}
        material={materials.뚜껑옆}
        position={[3.391, 5.679, 10.274]}
        rotation={[-Math.PI, 1.261, 0]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube040.geometry}
        material={materials.뚜껑옆}
        position={[8.762, 5.659, 6.34]}
        rotation={[-Math.PI, 0.624, 0]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube041.geometry}
        material={nodes.Cube041.material}
        position={[10.774, 5.655, 0.019]}
        rotation={[-Math.PI, 0, 0]}
        scale={[-0.059, -1.334, -3.483]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold.geometry}
        material={materials['GOLD meterial']}
        position={[10.888, 4.379, 0.013]}
        rotation={[1.584, 0.006, 1.563]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold001.geometry}
        material={materials['GOLD meterial']}
        position={[8.857, 4.379, -6.332]}
        rotation={[1.585, -0.003, 0.93]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold002.geometry}
        material={materials['GOLD meterial']}
        position={[10.888, 4.379, 0.013]}
        rotation={[1.584, 0.006, 1.563]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold003.geometry}
        material={materials['GOLD meterial']}
        position={[8.857, 4.379, -6.332]}
        rotation={[1.585, -0.003, 0.93]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold004.geometry}
        material={materials['GOLD meterial']}
        position={[3.502, 4.379, -10.336]}
        rotation={[1.581, -0.011, 0.304]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold005.geometry}
        material={materials['GOLD meterial']}
        position={[-3.144, 4.379, -10.315]}
        rotation={[1.572, -0.015, -0.33]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold006.geometry}
        material={materials['GOLD meterial']}
        position={[-10.75, 4.379, -0.024]}
        rotation={[1.557, -0.006, -1.578]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold007.geometry}
        material={materials['GOLD meterial']}
        position={[-10.75, 4.379, -0.024]}
        rotation={[1.557, -0.006, -1.578]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold008.geometry}
        material={materials['GOLD meterial']}
        position={[-3.293, 4.379, 10.375]}
        rotation={[1.561, 0.011, -2.837]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold009.geometry}
        material={materials['GOLD meterial']}
        position={[-10.75, 4.379, -0.024]}
        rotation={[1.557, -0.006, -1.578]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold010.geometry}
        material={materials['GOLD meterial']}
        position={[-8.809, 4.384, -6.284]}
        rotation={[1.563, -0.013, -0.936]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold011.geometry}
        material={materials['GOLD meterial']}
        position={[-10.855, 4.316, -0.009]}
        rotation={[1.557, -0.006, -1.566]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold012.geometry}
        material={materials['GOLD meterial']}
        position={[-8.849, 4.508, 6.382]}
        rotation={[1.556, 0.003, -2.181]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold013.geometry}
        material={materials['GOLD meterial']}
        position={[3.506, 4.403, 10.349]}
        rotation={[1.569, 0.015, 2.824]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wood_carvingdecor_molding_gold014.geometry}
        material={materials['GOLD meterial']}
        position={[8.876, 4.383, 6.414]}
        rotation={[1.578, 0.013, 2.187]}
        scale={-17.598}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.찐뚜껑.geometry}
        material={materials.LID}
        position={[-0.001, 5.337, -0.001]}
        scale={[11.276, 0.239, 11.276]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[-8.71, 6.619, -2.798]}
        rotation={[0.001, -0.306, 0.47]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere001.geometry}
        material={nodes.Sphere001.material}
        position={[-5.441, 6.619, -7.487]}
        rotation={[0.001, -0.95, 0.47]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere002.geometry}
        material={nodes.Sphere002.material}
        position={[-0.014, 6.619, -9.216]}
        rotation={[0.051, -1.561, 0.52]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere003.geometry}
        material={nodes.Sphere003.material}
        position={[5.432, 4.404, -3.677]}
        rotation={[2.735, -0.584, -0.235]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere004.geometry}
        material={nodes.Sphere004.material}
        position={[-8.71, 6.619, -2.798]}
        rotation={[0.001, -0.306, 0.47]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere005.geometry}
        material={nodes.Sphere005.material}
        position={[-5.441, 6.619, -7.487]}
        rotation={[0.001, -0.95, 0.47]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere006.geometry}
        material={nodes.Sphere006.material}
        position={[-0.014, 6.619, -9.216]}
        rotation={[0.051, -1.561, 0.52]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere007.geometry}
        material={nodes.Sphere007.material}
        position={[5.373, 6.619, -7.461]}
        rotation={[3.141, -0.946, -2.673]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere008.geometry}
        material={nodes.Sphere008.material}
        position={[-8.71, 6.619, -2.798]}
        rotation={[0.001, -0.306, 0.47]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere009.geometry}
        material={nodes.Sphere009.material}
        position={[-5.441, 6.619, -7.487]}
        rotation={[0.001, -0.95, 0.47]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere010.geometry}
        material={nodes.Sphere010.material}
        position={[-0.014, 6.619, -9.216]}
        rotation={[0.051, -1.561, 0.52]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere011.geometry}
        material={nodes.Sphere011.material}
        position={[5.373, 6.619, -7.461]}
        rotation={[3.141, -0.946, -2.673]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere012.geometry}
        material={nodes.Sphere012.material}
        position={[1.645, 10.433, 0.547]}
        rotation={[0.077, -0.343, -0.451]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere013.geometry}
        material={nodes.Sphere013.material}
        position={[1.039, 10.466, 1.26]}
        rotation={[-0.09, -0.915, -0.541]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere014.geometry}
        material={nodes.Sphere014.material}
        position={[0, 10.381, 1.754]}
        rotation={[-1.169, -1.455, -1.632]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere015.geometry}
        material={nodes.Sphere015.material}
        position={[-1.027, 10.525, 1.381]}
        rotation={[-3.075, -0.973, 2.705]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere016.geometry}
        material={nodes.Sphere016.material}
        position={[1.709, 10.417, -0.482]}
        rotation={[0.293, 0.153, -0.546]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere017.geometry}
        material={nodes.Sphere017.material}
        position={[-1.59, 10.479, 0.563]}
        rotation={[2.957, -0.203, 2.615]}
        scale={0.162}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere018.geometry}
        material={nodes.Sphere018.material}
        position={[0.611, 10.917, -0.862]}
        rotation={[0.026, -0.895, 0.043]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere019.geometry}
        material={nodes.Sphere019.material}
        position={[0.998, 10.917, -0.337]}
        rotation={[0.026, -0.895, 0.043]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere020.geometry}
        material={nodes.Sphere020.material}
        position={[-0.988, 10.917, 0.328]}
        rotation={[0.026, -0.895, 0.043]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere021.geometry}
        material={nodes.Sphere021.material}
        position={[-0.601, 10.917, 0.852]}
        rotation={[0.026, -0.895, 0.043]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere022.geometry}
        material={nodes.Sphere022.material}
        position={[-0.97, 10.917, -0.311]}
        rotation={[0.026, -0.895, 0.043]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere023.geometry}
        material={nodes.Sphere023.material}
        position={[-0.614, 10.917, -0.859]}
        rotation={[0.026, -0.895, 0.043]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere024.geometry}
        material={nodes.Sphere024.material}
        position={[0.004, 10.917, -1.046]}
        rotation={[0.026, -0.895, 0.043]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere025.geometry}
        material={nodes.Sphere025.material}
        position={[-0.004, 10.917, 1.05]}
        rotation={[0.026, -0.895, 0.043]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere026.geometry}
        material={nodes.Sphere026.material}
        position={[0.622, 10.917, 0.85]}
        rotation={[0.026, -0.895, 0.043]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere027.geometry}
        material={nodes.Sphere027.material}
        position={[1.003, 10.917, 0.323]}
        rotation={[0.026, -0.895, 0.043]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere028.geometry}
        material={nodes.Sphere028.material}
        position={[-6.536, 6.067, 9.353]}
        rotation={[1.97, -0.825, 0.531]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere029.geometry}
        material={nodes.Sphere029.material}
        position={[-6.231, 6.173, 9.451]}
        rotation={[1.97, -0.825, 0.531]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere030.geometry}
        material={nodes.Sphere030.material}
        position={[-0.464, 6.115, 11.296]}
        rotation={[1.97, -0.825, 0.531]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere031.geometry}
        material={nodes.Sphere031.material}
        position={[-0.246, 6.029, 11.375]}
        rotation={[1.97, -0.825, 0.531]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere032.geometry}
        material={nodes.Sphere032.material}
        position={[0.262, 6.012, 11.331]}
        rotation={[1.134, -0.81, -0.563]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere033.geometry}
        material={nodes.Sphere033.material}
        position={[0.554, 6.135, 11.234]}
        rotation={[1.134, -0.81, -0.563]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere034.geometry}
        material={nodes.Sphere034.material}
        position={[6.346, 6.115, 9.385]}
        rotation={[1.175, -0.827, -0.507]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere035.geometry}
        material={nodes.Sphere035.material}
        position={[6.596, 6.048, 9.303]}
        rotation={[1.174, -0.826, -0.508]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere036.geometry}
        material={nodes.Sphere036.material}
        position={[6.889, 5.996, 9.053]}
        rotation={[0.794, -0.502, -1.106]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere039.geometry}
        material={nodes.Sphere039.material}
        position={[7.032, 6.083, 8.831]}
        rotation={[0.794, -0.502, -1.106]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere040.geometry}
        material={nodes.Sphere040.material}
        position={[10.829, 5.901, 3.3]}
        rotation={[0.675, 0.003, -1.564]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere041.geometry}
        material={nodes.Sphere041.material}
        position={[10.816, 6.094, 2.994]}
        rotation={[0.675, 0.003, -1.564]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere042.geometry}
        material={nodes.Sphere042.material}
        position={[10.83, 6.072, -2.984]}
        rotation={[0.675, 0.003, -1.564]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere043.geometry}
        material={nodes.Sphere043.material}
        position={[10.828, 5.955, -3.287]}
        rotation={[0.675, 0.003, -1.564]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere044.geometry}
        material={nodes.Sphere044.material}
        position={[10.753, 5.956, -3.685]}
        rotation={[0.775, 0.466, -1.976]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere045.geometry}
        material={nodes.Sphere045.material}
        position={[10.581, 6.113, -3.902]}
        rotation={[0.775, 0.466, -1.976]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere046.geometry}
        material={nodes.Sphere046.material}
        position={[7.033, 6.08, -8.742]}
        rotation={[0.775, 0.466, -1.976]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere047.geometry}
        material={nodes.Sphere047.material}
        position={[6.832, 5.938, -9.014]}
        rotation={[0.775, 0.466, -1.976]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere048.geometry}
        material={nodes.Sphere048.material}
        position={[6.565, 5.895, -9.376]}
        rotation={[1.166, 0.823, -2.603]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere049.geometry}
        material={nodes.Sphere049.material}
        position={[6.364, 6.045, -9.422]}
        rotation={[1.166, 0.823, -2.603]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere050.geometry}
        material={nodes.Sphere050.material}
        position={[0.602, 6.056, -11.258]}
        rotation={[1.166, 0.823, -2.603]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere051.geometry}
        material={nodes.Sphere051.material}
        position={[0.329, 5.896, -11.361]}
        rotation={[1.166, 0.823, -2.603]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere052.geometry}
        material={nodes.Sphere052.material}
        position={[-0.126, 5.903, -11.42]}
        rotation={[1.971, 0.825, 2.628]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere054.geometry}
        material={nodes.Sphere054.material}
        position={[-0.346, 6.09, -11.35]}
        rotation={[1.971, 0.825, 2.628]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere053.geometry}
        material={nodes.Sphere053.material}
        position={[-6.127, 6.128, -9.401]}
        rotation={[1.971, 0.825, 2.628]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere055.geometry}
        material={nodes.Sphere055.material}
        position={[-6.376, 6.015, -9.325]}
        rotation={[1.971, 0.825, 2.628]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere056.geometry}
        material={nodes.Sphere056.material}
        position={[-6.855, 5.938, -9.088]}
        rotation={[2.346, 0.506, 2.04]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere057.geometry}
        material={nodes.Sphere057.material}
        position={[-6.968, 6.088, -8.909]}
        rotation={[2.346, 0.506, 2.04]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere058.geometry}
        material={nodes.Sphere058.material}
        position={[-10.499, 6.148, -4.084]}
        rotation={[2.346, 0.506, 2.04]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere059.geometry}
        material={nodes.Sphere059.material}
        position={[-10.73, 5.979, -3.787]}
        rotation={[2.346, 0.506, 2.04]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere060.geometry}
        material={nodes.Sphere060.material}
        position={[-10.916, 5.936, -3.367]}
        rotation={[2.466, -0.038, 1.55]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere061.geometry}
        material={nodes.Sphere061.material}
        position={[-10.92, 6.086, -3.066]}
        rotation={[2.466, -0.038, 1.55]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere062.geometry}
        material={nodes.Sphere062.material}
        position={[-10.922, 6.126, 2.998]}
        rotation={[2.466, -0.038, 1.55]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere063.geometry}
        material={nodes.Sphere063.material}
        position={[-10.922, 6.012, 3.279]}
        rotation={[2.466, -0.038, 1.55]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere064.geometry}
        material={nodes.Sphere064.material}
        position={[-10.848, 5.986, 3.66]}
        rotation={[2.373, -0.453, 1.18]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere065.geometry}
        material={nodes.Sphere065.material}
        position={[-10.682, 6.097, 3.88]}
        rotation={[2.373, -0.453, 1.18]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere066.geometry}
        material={nodes.Sphere066.material}
        position={[-7.136, 6.099, 8.793]}
        rotation={[2.373, -0.453, 1.18]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere067.geometry}
        material={nodes.Sphere067.material}
        position={[-6.958, 5.995, 9.038]}
        rotation={[2.373, -0.453, 1.18]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere068.geometry}
        material={nodes.Sphere068.material}
        position={[10.574, 6.067, 3.901]}
        rotation={[0.794, -0.502, -1.106]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere069.geometry}
        material={nodes.Sphere069.material}
        position={[10.739, 5.908, 3.686]}
        rotation={[0.794, -0.502, -1.106]}
        scale={0.101}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere070.geometry}
        material={nodes.Sphere070.material}
        position={[-0.091, 1.45, 1.775]}
        rotation={[-3.115, -1.273, 1.601]}
        scale={0.042}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere038.geometry}
        material={nodes.Sphere038.material}
        position={[0.971, 1.453, 1.496]}
        rotation={[-0.024, -1.239, -1.588]}
        scale={0.042}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere072.geometry}
        material={nodes.Sphere072.material}
        position={[1.732, 1.45, -0.462]}
        rotation={[-0.008, 0.033, -1.565]}
        scale={0.042}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere071.geometry}
        material={nodes.Sphere071.material}
        position={[0.099, 1.452, -1.81]}
        rotation={[-0.026, 1.271, -1.54]}
        scale={0.042}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere073.geometry}
        material={nodes.Sphere073.material}
        position={[-1.147, 1.447, 1.379]}
        rotation={[-3.132, -0.656, 1.582]}
        scale={0.042}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere074.geometry}
        material={nodes.Sphere074.material}
        position={[-1.675, 1.452, -0.662]}
        rotation={[-3.132, 0.607, 1.571]}
        scale={0.042}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere037.geometry}
        material={nodes.Sphere037.material}
        position={[5.182, 4.393, -4.04]}
        rotation={[-2.91, -0.621, 0.127]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere075.geometry}
        material={nodes.Sphere075.material}
        position={[6.812, 4.443, -0.369]}
        rotation={[-2.508, -0.002, -0.01]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere076.geometry}
        material={nodes.Sphere076.material}
        position={[6.704, 4.408, 0.227]}
        rotation={[2.805, -0.001, -0.002]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere077.geometry}
        material={nodes.Sphere077.material}
        position={[5.593, 4.442, 3.789]}
        rotation={[-2.009, 0.329, -0.571]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere078.geometry}
        material={nodes.Sphere078.material}
        position={[5.19, 4.345, 4.04]}
        rotation={[3.135, 0.672, -0.018]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere079.geometry}
        material={nodes.Sphere079.material}
        position={[2.566, 4.465, 6.696]}
        rotation={[-1.766, 0.515, -1.195]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere080.geometry}
        material={nodes.Sphere080.material}
        position={[-1.93, 4.423, 6.58]}
        rotation={[-0.913, 1.095, -2.288]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere081.geometry}
        material={nodes.Sphere081.material}
        position={[-5.541, 4.486, 4.459]}
        rotation={[-0.456, 0.616, -2.871]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere082.geometry}
        material={nodes.Sphere082.material}
        position={[-6.881, 4.456, 0.316]}
        rotation={[-0.371, 0.001, 3.14]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere083.geometry}
        material={nodes.Sphere083.material}
        position={[-6.09, 4.484, -3.964]}
        rotation={[-0.448, -0.58, 2.882]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere084.geometry}
        material={nodes.Sphere084.material}
        position={[-2.582, 4.521, -6.728]}
        rotation={[-0.882, -1.082, 2.319]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere085.geometry}
        material={nodes.Sphere085.material}
        position={[2.032, 4.46, -7.178]}
        rotation={[-2.239, -1.09, 0.841]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere086.geometry}
        material={nodes.Sphere086.material}
        position={[2.076, 4.42, 6.967]}
        rotation={[3.124, 1.266, -0.006]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere087.geometry}
        material={nodes.Sphere087.material}
        position={[-2.404, 4.412, 6.383]}
        rotation={[0.015, 1.223, 3.105]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere088.geometry}
        material={nodes.Sphere088.material}
        position={[-5.912, 4.379, 3.891]}
        rotation={[0.006, 0.622, 3.115]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere089.geometry}
        material={nodes.Sphere089.material}
        position={[-6.858, 4.389, -0.349]}
        rotation={[0.005, -0.006, 3.119]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere090.geometry}
        material={nodes.Sphere090.material}
        position={[-5.643, 4.403, -4.525]}
        rotation={[0.006, -0.636, 3.123]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere091.geometry}
        material={nodes.Sphere091.material}
        position={[-1.791, 4.462, -6.971]}
        rotation={[0.081, -1.253, -3.065]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere092.geometry}
        material={nodes.Sphere092.material}
        position={[2.689, 4.442, -6.984]}
        rotation={[3.126, -1.239, -0.037]}
        scale={0.063}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartouche_decor_molding001.geometry}
        material={materials['GOLD meterial.001']}
        position={[10.948, 7.202, -0.03]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={14.483}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartouche_decor_molding002.geometry}
        material={materials['GOLD meterial.001']}
        position={[8.917, 7.202, -6.376]}
        rotation={[-1.571, 0, -0.938]}
        scale={14.483}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartouche_decor_molding003.geometry}
        material={materials['GOLD meterial.001']}
        position={[10.948, 7.202, -0.03]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={14.483}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartouche_decor_molding004.geometry}
        material={materials['GOLD meterial.001']}
        position={[8.917, 7.202, -6.376]}
        rotation={[-1.571, 0, -0.938]}
        scale={14.483}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartouche_decor_molding005.geometry}
        material={materials['GOLD meterial.001']}
        position={[3.562, 7.202, -10.38]}
        rotation={[-1.571, 0, -0.311]}
        scale={14.483}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartouche_decor_molding006.geometry}
        material={materials['GOLD meterial.001']}
        position={[-3.143, 7.202, -10.433]}
        rotation={[-1.571, 0, 0.322]}
        scale={14.483}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartouche_decor_molding009.geometry}
        material={materials['GOLD meterial.001']}
        position={[-8.701, 7.202, -6.51]}
        rotation={[-1.571, 0, 0.937]}
        scale={14.483}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartouche_decor_molding010.geometry}
        material={materials['GOLD meterial.001']}
        position={[-10.883, 7.202, -0.02]}
        rotation={[-Math.PI / 2, 0, 1.57]}
        scale={14.483}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartouche_decor_molding011.geometry}
        material={materials['GOLD meterial.001']}
        position={[-8.876, 7.202, 6.337]}
        rotation={[-1.571, 0, 2.197]}
        scale={14.483}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartouche_decor_molding012.geometry}
        material={materials['GOLD meterial.001']}
        position={[-3.31, 7.202, 10.347]}
        rotation={[-1.571, 0, 2.83]}
        scale={14.483}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartouche_decor_molding007.geometry}
        material={materials['GOLD meterial.001']}
        position={[3.489, 7.226, 10.321]}
        rotation={[-1.571, 0, -2.831]}
        scale={14.483}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cartouche_decor_molding008.geometry}
        material={materials['GOLD meterial.001']}
        position={[8.859, 7.206, 6.387]}
        rotation={[-1.571, 0, -2.194]}
        scale={14.483}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding001.geometry}
        material={materials['Marble yellow']}
        position={[10.743, 4.478, 0.009]}
        rotation={[1.577, 0.003, -1.567]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding002.geometry}
        material={materials['Marble yellow']}
        position={[8.712, 4.478, -6.336]}
        rotation={[1.578, -0.002, -2.2]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding003.geometry}
        material={materials['Marble yellow']}
        position={[10.743, 4.478, 0.009]}
        rotation={[1.577, 0.003, -1.567]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding004.geometry}
        material={materials['Marble yellow']}
        position={[8.712, 4.478, -6.336]}
        rotation={[1.578, -0.002, -2.2]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding005.geometry}
        material={materials['Marble yellow']}
        position={[3.357, 4.478, -10.34]}
        rotation={[1.576, -0.005, -2.827]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding006.geometry}
        material={materials['Marble yellow']}
        position={[-3.289, 4.478, -10.319]}
        rotation={[1.571, -0.007, 2.823]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding007.geometry}
        material={materials['Marble yellow']}
        position={[-10.895, 4.478, -0.028]}
        rotation={[1.564, -0.003, 1.576]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding008.geometry}
        material={materials['Marble yellow']}
        position={[-10.895, 4.478, -0.028]}
        rotation={[1.564, -0.003, 1.576]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding009.geometry}
        material={materials['Marble yellow']}
        position={[-8.872, 4.478, 6.328]}
        rotation={[1.564, 0.002, 0.949]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding010.geometry}
        material={materials['Marble yellow']}
        position={[-3.438, 4.478, 10.29]}
        rotation={[1.566, 0.005, 0.316]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding011.geometry}
        material={materials['Marble yellow']}
        position={[-8.753, 4.478, -6.393]}
        rotation={[1.567, -0.006, 2.209]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding012.geometry}
        material={materials['Marble yellow']}
        position={[3.361, 4.502, 10.264]}
        rotation={[1.57, 0.007, -0.306]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Decor_molding013.geometry}
        material={materials['Marble yellow']}
        position={[8.731, 4.482, 6.33]}
        rotation={[1.575, 0.006, -0.943]}
        scale={7.849}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder020.geometry}
        material={materials.Material}
        position={[1.53, 1.849, 5.99]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.084, 0.104, 0.084]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder028.geometry}
        material={nodes.Cylinder028.material}
        position={[3.795, 2.516, -2.496]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.084, 0.104, 0.084]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder035.geometry}
        material={nodes.Cylinder035.material}
        position={[3.473, 2.516, 2.637]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.084, 0.104, 0.084]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder037.geometry}
        material={nodes.Cylinder037.material}
        position={[-1.533, 2.516, 4.152]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.084, 0.104, 0.084]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder038.geometry}
        material={materials['Material.003']}
        position={[-4.66, 4.099, -0.353]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.056, 1.337, 0.056]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder039.geometry}
        material={nodes.Cylinder039.material}
        position={[-4.656, 2.516, -0.356]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.084, 0.104, 0.084]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder041.geometry}
        material={nodes.Cylinder041.material}
        position={[-1.215, 2.516, -4.34]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.084, 0.104, 0.084]}
      />
    </group>
  )
})  

useGLTF.preload('/assets/Models/Utopia.glb')
