/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Model = forwardRef(function Model(props, ref) {
  const { nodes, materials } = useGLTF('/assets/Models/Liberation.glb')
  return (
    <group ref={ref} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={materials.rubywhite}
        position={[-0.023, 1.359, -0.392]}
        rotation={[0.043, 0.014, -0.015]}
        scale={[1, 0.823, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Icosphere.geometry}
        material={materials.Material}
        position={[0.587, 1.435, 0.155]}
        scale={[1.449, 1.134, 1.568]}
      />
    </group>
  )
})  

useGLTF.preload('/assets/Models/Liberation.glb')
