/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Model = forwardRef(function Model(props, ref) {
  const { nodes, materials } = useGLTF('/assets/Models/Love.glb')
  return (
    <group ref={ref} {...props}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sphere.geometry}
        material={materials.Material}
        position={[-0.009, 0.064, -0.015]}
        scale={-0.153}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus013.geometry}
        material={materials['Material.002']}
        position={[0.026, 0, -0.016]}
        scale={[0.284, 0.284, 0.253]}
      />
    </group>
  )
})

useGLTF.preload('/assets/Models/Love.glb')
